<div id="brandbar">
    <div id="brandbar-logo">

    </div>

    <div id="brandbar-content">
        Origam Demo:
        <select id="brandbar-menu" data-behaviour="open">
            <option value="">--select demo--</option>
        </select>
    </div>

    <div id="brandbar-buttons">
        <span data-width="full" title="Resize to full width" class="brandbar-resize origamicon origamicon-desktop"></span>
        <span data-width="768px" title="Resize to tablet width" class="brandbar-resize origamicon origamicon-tablet"></span>
        <span data-width="320px" title="Resize to phone width" class="brandbar-resize origamicon origamicon-mobile"></span>
    </div>
</div>